package zekusan.enums;

public enum Route {
	LOGIN,
	STUDENT_DASHBOARD,
	STUDENT_CATALOG,
	STUDENT_SETTINGS,
	LIBRARIAN_DASHBOARD,
	LIBRARIAN_CATALOG,
	LIBRARIAN_SETTINGS,
	LIBRARIAN_EDIT_ITEM,
	NOT_FOUND
}
