package zekusan.models.users;

public enum Permission {
	NONE,
	READ_ITEMS,
	CREATE_ITEMS,
	DELETE_ITEMS,
	MODIFY_ITEMS,
	READ_USERS,
	CREATE_USERS,
	DELETE_USERS,
	MODIFY_USERS,
	ACCEPT_PRENOTAZIONE,
	DELETE_PRENOTAZIONE,
	CREATE_PRENOTAZIONE
}
